"""
Tests for AFOS incremental-ingestion checkpoints.

Behaviors covered:
- Published timestamps become timezone-aware datetime objects.
- Timestamps with different offsets are normalized to UTC.
- Z-formatted timestamps are accepted.
- Missing timestamps return no checkpoint.
- Malformed and timezone-naive timestamps are rejected.
- Checkpoint extraction does not mutate the bronze record.
"""


def test_get_checkpoint_value_returns_datetime(): ...
def test_get_checkpoint_value_returns_utc_datetime(): ...
def test_get_checkpoint_value_accepts_z_suffix(): ...
def test_get_checkpoint_value_converts_offset_to_utc(): ...
def test_get_checkpoint_value_returns_none_when_missing(): ...
def test_get_checkpoint_value_returns_none_when_empty(): ...
def test_get_checkpoint_value_rejects_malformed_datetime(): ...
def test_get_checkpoint_value_rejects_naive_datetime(): ...
def test_get_checkpoint_value_does_not_mutate_record(): ...